### ISSUE TITLE
eslint: 'CONFIG' is not defined

### ISSUE THREAD

**Issue by icosamuel** [arthanzel/node-config-webpack#1]
In my `.js` files, eslint warns me that `'CONFIG' is not defined` even tho everything works fine.

I solved that with a `.eslintrc` global definition, but i'd recommend documenting it for future users
```javascript
{
  globals: {
    "CONFIG": false
  },
}

**Comment by arthanzel** [comment]
Super late response here, but the proper way to declare globals in ESlint is to use a `/* global */` directive at the top of our source file. Further docs here: https://eslint.org/docs/user-guide/configuring#specifying-globals
